### ISSUE TITLE
Padding a little bit weird

### ISSUE THREAD

**Issue by williambelle** [epfl-si/ckeditor-quote-epfl#6]
**Description**

The padding inside CKEditor is a little bit weird.

**Screenshots**

![Screenshot from 2020-07-17 16-43-59](https://user-images.githubusercontent.com/2843501/87799499-95d4a700-c84d-11ea-957d-a905ca71d401.png)

![Screenshot from 2020-07-17 16-43-58](https://user-images.githubusercontent.com/2843501/87799512-9a00c480-c84d-11ea-88ac-d10fdedf98e5.png)

**Comment by dragonleman** [comment]
It's not weird. I just left like it was, without the left vertical bar (for blockquote session) and padding. 

I'll look to modify this, having the same presentation with the final result.
